AKQATest/Models/AjaxResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AKQATest.Models
{
    public class AjaxResponse
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }

        public object Response { get; set; }
    }
}

AKQATest/Models/CurrencyWordsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AKQATest.Models
{
    public class PriceWordsModel
    {
        [Required(ErrorMessage = "First Name Required")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Price Required")]
        public double Price { get; set; }
    }
}

AKQATest/Controllers/HomeController.cs
using AKQATest.Models;
using AKQATest.Service;
using System.Web.Mvc;

namespace AKQATest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Index(PriceWordsModel currency)
        {
            var service = new CurrencyToWordsService(); //TODO: should have used dependency injector to get object
            var words = service.NumberToWords(currency.Price);

            var result = new AjaxResponse();

            if (string.IsNullOrEmpty(words))
            {
                result.IsSuccess = false;
                result.Message = "Error";
                result.Response = words;
                return Json(result);
            }
            else
            {
                result.IsSuccess = true;
                result.Message = "Price to words successfull";
                result.Response = words;
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

AKQATest/Controllers/WordsController.cs
using AKQATest.Models;
using AKQATest.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;

namespace AKQATest.Controllers
{
    public class NumberToWordsController : ApiController
    {
        [HttpPost]
        [Route("akqa/currencytowords")]
        public IHttpActionResult ToWords(PriceWordsModel currency)
        {
            var service = new CurrencyToWordsService();
            var words = service.NumberToWords(currency.Price);

            var result = new AjaxResponse { IsSuccess = true, Message = "Price to words successfull", Response = words };

            return Ok(result);
        }
    }
}

AKQATest/Views/Home/Index.cshtml
@model AKQATest.Models.PriceWordsModel
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>AKQA Test</h1>
    <p class="lead">To demonstrate basic mastery of modern web development with .NET/C# and give some insight into development practice.</p>
</div>

<div class="row">
    <div class="col-md-8">
        <h2>User Entry</h2>
    </div>
</div>

@using (Html.BeginForm("ToWords", "NumberToWords", FormMethod.Post, new { @id = "frmCurrency" }))
{
    <div class="row form-group">
        <div class="col-md-3 col-sm-2">
            <label id="lblName">Enter Name:</label>
        </div>
        <div class="col-md-6 col-sm-4">
            @Html.TextBoxFor(m => m.Name)
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-3 col-sm-2">
            <label id="lblCurrency">Enter Price:</label>
        </div>
        <div class="col-md-6 col-sm-4">
            @Html.TextBoxFor(m => m.Price)
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <input type="submit" class="btn btn-primary" id="btnSubmit" value="Submit" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col-md-8">
            Result:<label id="lblResult">Result here...</label>
        </div>
    </div>
}

AKQATest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>